name:                reduce
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/ucla-pls/reduce#readme
license:             BSD3
author:              Christian Gram Kalhauge
maintainer:          kalhauge@cs.ucla.edu
copyright:           MIT
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - containers
  - vector
  - mtl
  - transformers
  - contravariant >= 1.4.1

library:
  source-dirs:      src

benchmarks:
  reduce-stats:
    main: StatsMain.hs
    source-dirs: benchmark/stats
    dependencies:
      - reduce
      - random
      - attoparsec
      - text
      - optparse-applicative
      - cassava
      - bytestring

tests:
  reduce-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - reduce
      - tasty
      - tasty-hspec
      - tasty-hunit
      - tasty-discover
      - tasty-quickcheck
      - QuickCheck
      - filepath
      - directory
      - text
      - generic-random
      - hspec-expectations-pretty-diff
