name:                red
version:             0.1.0.0
github:              "kalhauge/reduce"
license:             BSD3
author:              "Christian Gram Kalhauge"
maintainer:          "kalhauge@cs.ucla.edu"
copyright:           "MIT"

extra-source-files:
- README.md
  # - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kalhauge/reduce#readme>

dependencies:
- base >= 4.7 && < 5
- reduce
- reduce-util
- optparse-applicative
- text
- mtl
- bytestring
- lens
- contravariant
- unliftio
- cassava
- vector
- filepath
- dirtree
- directory
- aeson
- language-c
- pretty
- containers
- pretty-simple

library:
  source-dirs: src

executables:
  red:
    main:                Main.hs
    source-dirs:         .
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - red
      - reduce-util
      - reduce
      - optparse-applicative

tests:
  red-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - red
    - hspec
